### ISSUE TITLE
MacVim hangs when opening a file with PeepOpen

### ISSUE THREAD

**Issue by adamlogic** [topfunky/PeepOpen-Issues#127] opened 2010-08-14 12:09 UTC
PeepOpen seems to work fine if I've already opened a file for editing, but not if there are no files open yet.  This might not be major if it just failed to open, but it's actually hanging MacVim and forcing me to quit and restart.

I've narrowed down this issue to the "filetype plugin on" setting in my .vimrc (or "filetype plugin indent on").  I've removed all other plugins and configuration, and removing this one line will fix the issue. 

Here are the steps I go through to create the issue:
1. Open MacVim by typing "mvim" in a project directory.  (This also happens if I launch the MacVim application and :cd to the directory)
2. Activate PeepOpen
3. Select a file and hit enter
4. PeepOpen goes away, and my MacVim window is completely unresponsive.  I have to quit MacVim at this point.

I'm using MacVim snapshot 52 and PeepOpen 0.2.3.  PeepOpen is the only thing in my .vim directory, "filetype plugin on" is the only line in my .vimrc, and I have no .gvimrc.

**Comment by adamlogic** [comment] 2010-08-14 12:26
Also, I just discovered that it's important which type of file gets opened before using PeepOpen.  For example, if I launch MacVim, edit my README.md file, then trying using PeepOpen, it still hangs.  If I edit a Ruby or HAML file, though, PeepOpen will work fine on subsequent attempts.

**Comment by adamlogic** [comment] 2010-08-14 12:41
A bit more info about filetypes.  This seems to only happen with files that contain Ruby.  I can consistently hang MacVim by trying this with .rb, .erb, and .haml files.  Any other filetype I've tried, though (.js, .vim, .h, .md), seems to work fine.

**Comment by stevenharman** [comment] 2010-09-03 15:09
I am seeing the same behavior Adam is describing - and can reproduce using the same steps.

**Comment by ivar** [comment] 2010-09-22 07:34
This is biting me too - thanks adamlogic for tracking down so much.
Also, this is a duplicate of issue #100

**Comment by adamlogic** [comment] 2010-09-28 13:52
This is not a bug with PeepOpen, but rather MacVim, and it was fixed [here](http://github.com/b4winckler/macvim/commit/f4e9d096f28b055839a24df57e8b46a0897ba45b).  The fix hasn't made it into a released version of MacVim yet, so you have to built it yourself using the instructions [here](http://github.com/b4winckler/macvim/wiki).

**Comment by stevenharman** [comment] 2010-09-28 15:14
Thanks for the update, adam!

**Closed as completed** 2010-09-28 20:52 UTC
