### ISSUE TITLE
blank peepopen box

### ISSUE THREAD

**Issue by arpancj** [topfunky/PeepOpen-Issues#8] opened 2010-04-13 20:57 UTC
I'm getting a blank box when peep-open opens. 

I've done the standard stuff. Open a project, open a file, and then press cmd+T. Peepopen opens, but nothing happens. If I go back to TextMate and press cmd+T again, I get the peep-open box, but it's blank, and does not allow me to type in anything.

I'm on the newest version of Textmate (1.5.9 (1510)), & Mac OS X 10.6.3. I can send a screenshot if necessary-but it's just peep-open without any text.

**Comment by arpancj** [comment] 2010-04-13 21:01
Oh, just checked the screenshot on Peepcode, and the box that opens does not display a search box on my system.

**Comment by topfunky** [comment] 2010-04-14 00:28
I was unable to reproduce this problem. 

For my benefit, could you drag a directory of files onto the PeepOpen icon? This should show the search window populated with files to search.

**Comment by arpancj** [comment] 2010-04-14 08:41
No change. Get the same blank box.

**Comment by topfunky** [comment] 2010-04-15 22:48
Weird. I'm not sure what's causing it or how to fix this. I'm glad to refund your purchase price...email boss@topfunky.com

Or, other questions:
- What hardware are you using (specifically, CPU)?
- What kind of project is being browsed? (Rails, Ruby gem, Xcode, shell scripts) It could be that all the files are being ignored.

**Comment by arpancj** [comment] 2010-04-19 19:14
- Core 2 Duo 2.4Ghz Macbook Pro (MacBookPro3,1)
- Rails Project

I really like the concept of this app, and am willing to wait for the next release to see if that one will work.

**Comment by arpancj** [comment] 2010-07-03 11:00
Specs: PeepOpen 0.21, OS X 10.6.4, Textmate 1.5.9 (1589) without any other plugins.

All libraries (ruby, git etc are installed via MacPorts. I do not have macruby installed)

Overall: peepopen file select box responds sluggishly.

With "Use Animation" checkbox deselected: gets stuck on this screen: 01. peepopen-animation-off.png

With "Use Animation" checkbox selected: get this screen: 02.png

When I type anything
- input box remains blank (same as 02.png)
- but when I press enter
  - if a file matches the text I typed, the file opens in textmate (after a second)
  - if no file matches, I get this error: "No text Editor found." 03.png
  - it appears that typing, scrolling etc. is working in the background, but the interface isn't updating
- other times, peepopen box opens with the text that was typed in the last time.

From Xcode: When I follow the instructions and attempt to access PeepOpen, I get this error: (05.png)
Uncaught Exception: **\* -[NSCFString substringWithRange:]: Range or index out of bounds

Finally, PeepOpen is unable to find the git executable on my system.  I have git installed using MacPorts (04.png) and it works from the terminal or textmate.

I really would like to use PeepOpen, but am unable to figure out why these problems are occurring on my system. If you have any ideas of what I should try, please let me know.

(I'm emailing the files to you. I'll also upload to dropbox and post the link here)

**Comment by arpancj** [comment] 2010-07-03 11:01
I get this error in the console:
PeepOpen[590]   -[NSNull screenFontWithRenderingMode:]: unrecognized selector sent to instance 0x1013a1000

Any idea what this means, and how I can resolve it?

**Comment by arpancj** [comment] 2010-07-03 11:04
BTW, I am using FontAgent Pro to manage fonts.

**Comment by arpancj** [comment] 2010-07-03 11:12
I've figured out the problem.

Changed FuzzyCell.rb (line 147) from Futura-CondensedMedium to Helvetica and everything suddenly works. I guess PeepOpen was trying to use a font that wasn't installed.

**Comment by arpancj** [comment] 2010-07-03 11:18
Glad I didn't ask for the refund. Liking PeepOpen so far. Using rails and getting a list of 40 new.html.erb files and having to search for the file I want was frustrating. Now don't need to deal with that anymore! :-)

**Comment by nickstenning** [comment] 2011-03-19 12:28
This issue still exists with the current version of PeepOpen. I happened to have Futura disabled, and this hangs PeepOpen with no useful error message presented to the user. Perhaps you could ship the `.ttf` with PeepOpen? Or at least let the user know what's happened and why they shouldn't have disabled the font!

**Comment by topfunky** [comment] 2011-03-21 19:19
That's useful to know. Futura is standard so I assumed it could be used. I'll try disabling it on my machine and figure out a solution.

**Comment by topfunky** [comment] 2011-03-22 00:43
The missing Futura issue has been fixed in the upcoming 0.3.1 release.

**Closed as completed by topfunky** 2011-03-22 00:43 UTC
Labels: Bug, v0.3.1
