### ISSUE TITLE
Instability when updating file list

### ISSUE THREAD

**Issue by rk** [topfunky/PeepOpen-Issues#128] opened 2010-08-16 22:45 UTC
I'm using PeepOpen 0.2.3 with TextMate 1.5.9 (1589) on a Mac with Snow Leopard 10.6.4.  When I hit CMD-R it refreshes the file list, but if I've refreshed 1 time already it becomes likely that it will freeze.  So far it ranges between 2 and 5 refreshes before PeepOpen crashes.

What do you need from me to troubleshoot this?

**Comment by ncr** [comment] 2010-08-21 15:11
Having the same issue under the same conditions.

**Comment by topfunky** [comment] 2010-09-01 20:57
I'm hearing similar reports on some machines and projects. It's important to me that PeepOpen be rock solid, so I'm hoping to be able to recreate the bug soon and fix it.

**Comment by rk** [comment] 2010-09-01 21:03
I'd state the circumstances myself, but for some reason I cannot duplicate the issue any longer.  It may be related to the repository, or a file.

**Comment by ncr** [comment] 2010-09-01 22:05
I've noticed that it happens more often when I type cmd-t and cmd-r pretty fast. if I wait between those two it happens rarely (but still). 

Update: after typing cmd-t, there's "loading..." at the bottom of the window which then becomes "xx records". typing cmd-r when it still says "loading..." triggers the bug.

**Comment by tjmcewan** [comment] 2010-09-24 13:34
I see two problems:
1. It doesn't refresh the cache when I re-open TextMate (if the directory/project hasn't changed?), hence I need to cmd-R - my file contents invariably have changed since my last cmd-T.
2. Calling refresh too quickly (after cmd-T), or too much causes it to hang - repeatably.

I'm in the habit of no. 2, because of  no. 1.

My observations:
-   if you have only one file in your project, you can hold cmd-R down almost indefinitely (it's basically sending lots of refresh commands per second)
-   the more files you have, the shorter period of time you can hold cmd-R down for, before it hangs
-   the presence of a .gitignore (in the same directory, in my tests) dramatically reduces the time before hang

Hence, opening even a new rails project and holding down cmd-R will trigger it to hang (almost straight away).  The only way out is to kill the PeepOpen process.

Of course, during normal operation no one holds down cmd-R, but it makes the bug reproducible.

By the way, I'm on 0.2.4 now.  Happy hunting!

**Comment by topfunky** [comment] 2010-09-29 18:03
Thanks for the detailed report.

I intentionally tested with holding down Cmd-R and fixed some threading bugs that caused crashes. However, it sounds like I need to try with bigger projects and deeper subdirectories.

**Comment by inspire22** [comment] 2010-10-08 01:03
woohoo! other people have the same problem I do.

My project has about 1300 files, so pretty big.  Reloading works a few times then I have to force-kill it.  Seems to sometimes happen even without reloading, though I haven't been able to figure out what causes it.

Sometimes when I type cmd+t then immediately a search term, its a bit slow, then the text goes into my editor still, and peepopen seems to be a bit more slow/angry after that.

**Comment by robincurry** [comment] 2010-11-30 18:58
I have similar issues. I'm using PeepOpen (which I love btw) version 0.2.4 with MacVim. I'm using it on several medium-sized rails projects, and I've set it to track 500 documents. I see the problems in primarily three situations:

1) if I type the shortcut to open PeepOpen (in my case, leader-t) and then immediately start typing the name of the file I want to open while it still says 'loading...'

2) like many of the cases above, when I do a refresh.

3) when I switch to a different project

This problem started out small - maybe hanging every once in awhile. Now, I'm having to force kill PeepOpen 5-10 times a day.

**Comment by inspire22** [comment] 2010-11-30 19:00
For me, patience has helped reduce this problem - I don't restart peepopen at all now.

If its being slow, I just wait for it.  I can change to another program, then when i come back and it's done, I find the window (often under textmate), then close it (it doesn't work to choose the file anymore as it stopped waiting for itself).

Then when I do a new search it'll be fast again.  I think it has something to do with the index being paged out of ram, so then it takes too long and something inside times out.

**Comment by tjmcewan** [comment] 2010-11-30 22:05
I have one particular project that it won't load on (and sorry Inspire22, I'm not going to wait for it).  @topfunky is there a cache or index PO keeps that I can obliterate?

**Comment by alecthomas** [comment] 2010-12-03 01:51
I have the same issue quite often. The only recourse is to drop to a shell and kill the process.

Anecdotally, it seems to trigger more frequently if I start typing before the refresh has finished. This may be just my imagination though.

**Comment by robincurry** [comment] 2011-01-07 22:28
fyi, based on my observation that the issues I was seeing had gotten considerably worse over time, even though my app had not grown all that much in relation, I had a thought that perhaps the issue was related to the project's growing git commit history. I turned off "show metadata with files" under SCM in the Preferences and KABLAM!, no more problems!

I did so love that feature, but, until this issue is resolved, note that turning it off might be a viable workaround.

**Comment by nanno77** [comment] 2011-01-14 19:13
I too am having this same problem. Only on my macbook. I can open the same project on my mac pro without any issues. For me it seems to be a problem no matter how large the project is. Hopefully this can be resolved soon. 

Turning off the "show metadata with files" preference had no impact on the load.

**Comment by nanno77** [comment] 2011-01-17 19:33
I found that if I turn off the "Show Filetype Icons" my problem goes away. That is really bizarre.

**Comment by asanghi** [comment] 2011-02-04 12:52
My application only has 334 text files (after the filters) and i can reproduce the problem with the "Show metadata with files" option checked. If I uncheck it, and restart PeepOpen it work. If i select this option then it hangs. 

What does "Show metadata with files" do? -- Update: Never mind, yes i know what it does! But as reported by @robincurry 2 comments up, unselecting it is my workaround.

**Comment by akahn** [comment] 2011-02-23 17:39
Still experiencing this... I would love for PeepOpen to be rock solid.

At first, it seems what nanno77 says is true: turning off the 'show filetype icons' setting prevents this crash. But upon further testing, it's still easy to make peepopen crash. Try refreshing while the file list is being built. Crash.

**Comment by topfunky** [comment] 2011-03-05 00:25
We just published 0.3.0 which fixed a bunch of freezing and crashing issues. Give it a shot.

**Closed as completed by topfunky** 2011-03-05 00:25 UTC
Labels: Bug, v0.2.5
