### ISSUE TITLE
Cannot enable the Git Metadata

### ISSUE THREAD

**Issue by conradwt** [topfunky/PeepOpen-Issues#45] opened 2010-05-05 20:14 UTC
Hi, on the site, it shows the Git information for each file.  However, I wasn't able to enable/invoke this functionality.  The following appears on the product website:

The initial prototype performs a fuzzy search on paths and lists file modification dates.

**Comment by topfunky** [comment] 2010-05-05 21:16
It should appear automatically, but might not be able to find your local copy of git.

If you type "which git" in the Terminal, what does it say?

Also, it uses this command to retrieve the number of changed lines. Does this show any output (in Terminal, in a repository with changes)?

```
git diff --numstat
```

**Comment by vesan** [comment] 2010-05-23 10:00
Hi, Git information doesn't show for me either.

Terminal output:
    → which git
    /usr/local/bin/git

```
→ git diff --numstat
1       1       README.markdown
```

I use TextMate and ProjectPlus plugin should also show Git status for files and it doesn't. This is a new computer and on my previous one ProjectPlus worked so it suggests that something is wrong with my Git setup. I installed it from Homebrew and on commandline and GitX it works fine.

If you need any information to get this fixed, I'm willing to help.

**Comment by vesan** [comment] 2010-05-23 10:37
I installed PeepOpen to the older computer where ProjectPlus works and Git information didn't show. Terminal output from that machine:

```
→ which git
/usr/local/git/bin/git
```

`git diff --numstat` works also there. On the older machine git version is 1.6.4.1 and newer is 1.7.1. Older machine's git is installed with the OS X one click installer.

Is there any logging output I could enable to get a clue what the problem is?

**Comment by vesan** [comment] 2010-05-23 10:59
Sorry to spam like this...

I got ProjectPlus to work. My TextMate TM_GIT shell variable was incorrect.

Also I did find PeepOpen error message in Console.app `/bin/sh: git: command not found`. I symlinked the /usr/local/bin/git to /usr/bin/git and Git diff info started showing in PeepOpen. Great!

I don't know if my setup is unusual but I think git binary in /usr/local/bin should work or at least it would be nice to have information about the correct path in help files.

**Comment by topfunky** [comment] 2010-05-26 20:34
I also need to add more debugging information to PeepOpen if it can't find Git. Someone else also reported a similar problem.

**Comment by jjb** [comment] 2010-06-06 23:58
I'm having the same problem. git is in my path, and diff --numstat behaves as expected, but no git features in peepopen.

**Comment by tbassetto** [comment] 2010-06-16 10:51
Hi, same problem for me. `git diff --numstat` works and git is located at `/usr/local/git/bin/git`

While waiting for a patch, a created a symlink: `sudo ln -s /usr/local/bin/git /usr/bin/git`

**Comment by furstenberg** [comment] 2010-06-22 09:12
What the others said. No Git found. ProjectPlus works fine and git diff --numstat works.

**Comment by SFEley** [comment] 2010-07-16 19:01
Likewise. I _think_ this is a shell paths problem. Those of us setting paths in our .bashrc or .zshrc or wherever are probably seeing this error because those are only run for interactive shells (i.e., from Terminal and such) and the PeepOpen application, when it launches, isn't running those scripts. Hence, it doesn't have the full path you're used to having on your command line.

I tested this.  My git is in `/usr/local/bin`, which is set in my **.zshrc** file.  Launching PeepOpen from Spotlight, or letting it automatically launch when TextMate runs, I'm seeing this in version 0.2.1:
![No git found, sadness](http://img.skitch.com/20100716-gt8uw7dqryaukner63urw4d47d.png)

However, if I quit that and then run `open /Applications/PeepOpen.app` from the command line, I see this:
![Git found, yay!](http://img.skitch.com/20100716-mscpqdj5b2fi1rwdiqpdsxn6un.png)

I suppose this could be fixed by having all PeepOpen users put all their paths in .profile files instead, but I think it's a bit too much to expect. Instead, PeepOpen should use a tiered discovery process. If the currently implemented attempt to find git fails, it can try the following (possibly in this order):
1. Invoke the user's preferred shell and run `which git` in that;
2. Look for the executable in several common directories (/usr/local/bin, /opt/local/bin, etc.);
3. Provide a file selection dialog and let the user tell PeepOpen where git is.

Actually, the third option should probably be implemented anyway.  However it's found, the location of git should be stored in the preferences so that this work doesn't have to be repeated every time, and the full path should be used whenever git is invoked.

**Comment by akahn** [comment] 2010-07-20 21:35
Thanks for clarifying this issue, SFEley. I also have git in `/usr/local/bin`, since this is where homebrew installs it. topfunky, is there going to be a fix for this?

Thanks,
Alex

**Comment by eventualbuddha** [comment] 2010-07-23 15:45
Same issue here. I agree with SFEley's suggestions.

**Comment by josegonzalez** [comment] 2010-07-25 17:39
I actually have the TM_GIT Shell Variable set so I can use homebrew's git with the Git bundle. I assumed PeepOpen would do similar.

**Comment by topfunky** [comment] 2010-07-26 23:56
I'm hoping to use your shell's PATH so you don't have to do any extra configuration.

Cocoa doesn't have this capability built-in, but I think I can implement it using information available through the operating system.

**Comment by eventualbuddha** [comment] 2010-07-27 14:05
I'd be happy to test. I use the fish shell, so I think it'd work well as an edge case.

**Comment by bensie** [comment] 2010-07-28 20:08
Had the same issue, but adding TM_GIT /usr/local/bin/git Shell Variable got it working for me.

**Comment by topfunky** [comment] 2010-07-28 20:58
Version 0.2.3 has just been released and uses your choice of shell to find Git. If you can use git from your terminal, PeepOpen should now automatically find your copy of git without any extra configuration.

**Closed as completed** 2010-07-29 03:58 UTC
Labels: Bug

**Comment by louismrose** [comment] 2010-07-29 10:02
I've just purchased PeepOpen and ran into this issue. Updating to 0.2.3 fixed it for me. Thanks!

**Comment by jjb** [comment] 2010-07-29 10:27
the problem persists for me
- peepopen is finding my git in /opt/local/git
- `git diff --numstat` behaves as expected

But I don't get any metadata shown in peepopen.

I even tried making a symlink from /usr/bin/git to /opt/local/bin/git, and peepopen found it, but same behavior.

topfunky -- are you sure that the correct behavior of `git diff --numstat` is the only requirement? I installed git from macports -- maybe some feature/library is missing from that build?

Anyone else on this ticket have macports git working with peepopen?
