### ISSUE TITLE
Hide from dock

### ISSUE THREAD

**Issue by cmer** [topfunky/PeepOpen-Issues#41] opened 2010-04-28 14:59 UTC
You should allow us to hide the app from the dock.

**Comment by marktran** [comment] 2010-04-29 18:57
This is a duplicate of: http://github.com/topfunky/PeepOpen-Issues/issues#issue/3

**Comment by topfunky** [comment] 2010-04-30 17:54
Fixed in development and will be released in an update next week. It will be a menu bar app only (with possibly an option to remove that, too).

**Closed as completed by topfunky** 2010-04-30 17:54 UTC

**Comment by cmer** [comment] 2010-04-30 18:01
Amen.
