### ISSUE TITLE
[BUG] Changes working directory with mac vim

### ISSUE THREAD

**Issue by xaviershay** [topfunky/PeepOpen-Issues#62] opened 2010-05-19 23:23 UTC
I open macvim in the root folder for my project. Often (but not always I don't think), when I open a file with peepopen, it changes the local directory so next time I try to open a file in a different directory I can't.

First peepopen:
app/views/a/index.html

Second:
Can only select files in app/views/a (index, show, etc...)

**Comment by sinefunc** [comment] 2010-05-25 05:26
I second this one. I haven't upgraded to 0.1.9 because of this. Is this fixed?

**Comment by gf3** [comment] 2010-05-26 18:46
+1 I'm also experiencing this issue. On `0.2.0`.

**Comment by jhenderson** [comment] 2010-05-30 19:33
This is a major bug that needs sorting ASAP.

**Comment by miketaylr** [comment] 2010-06-01 16:39
Pretty please fix this issue.

**Comment by cowboy** [comment] 2010-06-01 16:41
A fix for this would be super-duper!!

**Comment by fermion** [comment] 2010-06-01 17:01
Oh man I would <3 for this to be fixed.

**Comment by Veejay** [comment] 2010-06-01 17:36
Happened to me as well, I'd be glad to see this bug fixed.

**Comment by millsb** [comment] 2010-06-03 02:31
Also happening to me. Seems like a fairly major issue for vim users.

**Comment by sinefunc** [comment] 2010-06-04 05:26
Please please please please \* 100000000000?

**Comment by gf3** [comment] 2010-06-25 16:45
Still experiencing the issue on `0.2.1`. Fix coming soon?

**Comment by topfunky** [comment] 2010-06-28 21:34
I thought this had been fixed and haven't been able to reproduce the bug. I'll give it another shot for the next update of PeepOpen.

**Comment by gf3** [comment] 2010-06-29 15:27
FWIW I'm not using that auto-chdir plugin for git repos.

**Comment by shemerey** [comment] 2010-07-05 16:17
Please Please Please fix it, it so vary useful program but it have terrible bug %-(

**Comment by akahn** [comment] 2010-07-21 14:05
I experience this bug when I first launch MacVim via the command line (`mvim`). When I open app/models/event.rb via PeepOpen, the next time I open PeepOpen, only files in app/models will be available. However, if I use the Vim command `:cd ../..` to change the working directory back to the project root, PeepOpen will not change the working directory after that, everything works correctly from then on.

**Comment by topfunky** [comment] 2010-07-21 22:19
I've tried various configurations but haven't been able to reproduce this bug. Can someone record a short sample of the conditions under which you experience this bug, and what version of MacVim you're using? http://screenr.com/

**Comment by millsb** [comment] 2010-07-22 00:54
I've got a video here. Opening up a rails app folder, selecting one file with PeepOpen, and then trying to open a second file, but the list comes up empty. http://screenr.com/DCX

**Comment by virgild** [comment] 2010-07-28 21:01
The same thing happens in 0.2.2.

**Comment by scottillogical** [comment] 2010-07-29 11:30
Broken for me to, is there any way to download an older version?

**Comment by formandmethod** [comment] 2010-07-29 14:51
This makes PeepCode mostly useless when used with MacVim.  I'm using the latest snapshot of MacVim 7.2 (http://macvim.googlecode.com/files/MacVim-snapshot-52.tbz) with PeepOpen 0.2.3.  I've been using the vim settings available here: http://github.com/twerth/dotfiles

UPDATE:  As akahn pointed out (below) there's a work-around (above) by using :cd to navigate back to the root of the project (which one needs to do only once).

**Comment by akahn** [comment] 2010-07-29 14:57
I disagree that this bug renders MacVim mostly useless. There is a very easy workaround for this bug (which I still hope will be fixed). After opening a file via PeepOpen, use `:cd` to navigate back to the root of your project. After that when you open PeepOpen, all your project's files will be available.

Alex

**Comment by topfunky** [comment] 2010-07-29 18:45
I still haven't been able to reproduce this, but obviously it's a problem for a lot of people. I'll try with twerth's dotfiles and hope to fix it for the next release.

**Comment by alecthomas** [comment] 2010-07-30 00:06
I've noticed this behaviour too. It only seems to trigger when initiating PeepOpen from the initial empty buffer. After you open a file with ":e <file>", or if you initiate PeepOpen from a new tab, it doesn't occur.

**Comment by akahn** [comment] 2010-07-30 14:43
Excellent, I hadn't noticed that. I typically start MacVim from the terminally using the `mvim` script that it comes with. I use no arguments, so I'm starting with a blank buffer in the root of a project. Topfunky, try starting MacVim in that way and then maybe you'll be able to reproduce this behavior.

**Comment by scottillogical** [comment] 2010-07-30 19:27
I just whiped and installed snow leopard (for a seperate reason) immediately installed macvim snapshot 52, peepopen 0.2.3, and now when I open a file in a rails directory and fire peepopen, it shows me a bunch of files not in the rails directory and searching for files in the rails directory does nothing.  it's actually stuck on a bunch of files in my .dropbox directory

**Comment by topfunky** [comment] 2010-07-30 21:22
@scottschulthess: It sounds like MacVim is still using your home directory as the working directory and is sending that to PeepOpen.

Use ":cd ~/my/project" to set vim's working directory, or use a plugin like http://github.com/airblade/vim-rooter that sets vim's working directory based on the discovery of a .git directory (when you open Ruby or other source files).

**Comment by scottillogical** [comment] 2010-08-02 20:31
@topfunky that fixed it for me, thanks

**Comment by felixge** [comment] 2010-08-06 09:27
+1 for getting this fixed. Another way I can reproduce this is:

Open MacVim from Finder
cd /my_project
:pwd -> /my_project
Peeopen /my_project/sub_dir/my_file.txt
:pwd -> /my_project/sub_dir

The same thing happens if I launch MacVim from terminal with no arguments as described by others.

**Comment by arthurgeek** [comment] 2010-08-09 23:25
This bug happens to me as well. Launch MacVim using the command line, open a file via PeepOpen. It changes the directory.

**Comment by indiefan** [comment] 2010-08-13 23:11
This would be great.

**Comment by felixge** [comment] 2010-08-27 11:28
Are you still looking into this? I just tried to narrow down the problem and moved my ~/.vim, ~/.vimrc and ~/.gvimrc to different places.

No luck, even with just peepcode installed and nothing else, I'm hitting this problem.

My system: OSX 10.6.4, MacVim 7.3 (Snapshot 53). I recently upgraded to 7.3, the problem already existed in 7.2 (snapshot 52).

**Comment by ozataman** [comment] 2010-08-28 13:02
+1 - Having the same issue with 0.2.3. Doesn't happen all the time but happens often enough to be annoying.

**Comment by daviddavis** [comment] 2010-09-01 13:44
I tried rooter.vim to no avail. It seems to happen when I open macvim and cd to a directory and then run PeepOpen. When I start from the console by running mvim it doesn't happen. I made a video too.

http://cl.ly/a5adb3ee74f80e003d72

**Comment by miketaylr** [comment] 2010-09-01 13:59
I've been using the Command-T plugin rather than PeepOpen, I suggest others use it while this issue is still open:

http://www.vim.org/scripts/script.php?script_id=3025

**Comment by scottillogical** [comment] 2010-09-01 14:15
I don't get the issue, when I cd into a directory then peepopen to a file, and do a pwd, the current working dir doesn't change...

**Comment by devth** [comment] 2010-09-01 20:50
I only started experiencing this behavior after upgrading to MacVim 7.3.

**Comment by ozataman** [comment] 2010-09-01 20:57
Same here - started experiencing the issue after the latest MacVim upgrade.

**Comment by felixge** [comment] 2010-09-05 16:12
The issue does not seem to appear anymore if I open my project using like this:

```
 cd /project
 mvim .
```

However, this does not work:

```
mvim /project
```

Nor does:

```
cd /project
mvim
```

Anyway, this seems like a reasonable workaround for me right now.

**Comment by b4winckler** [comment] 2010-09-30 10:45
Guys, I think this is related to the fact that MacVim changes directory for the first file opened.

If you open a new window (Cmd+N) then use PeepOpen the directory will change.

If you open a new window and a file (Cmd+O, "mvim filename", ...) then the directory will not change when you use PeepOpen.

This behavior is by design, see [this thread](http://groups.google.com/group/vim_mac/browse_thread/thread/53525335a61faa74).  If you want to discuss this issue further, please know that it is not a PeepOpen bug and hence should be discussed on the [vim_mac](http://groups.google.com/group/vim_mac) Google group (where all MacVim discussions take place).  Thanks.

**Comment by alecthomas** [comment] 2010-10-02 01:30
That is good to know, thank you. I've repled in the thread (though it hasn't appeared yet; it may be moderated).

**Comment by b4winckler** [comment] 2010-10-03 16:00
Everybody following this issue will be happy to know that I've changed the behavior of MacVim now, see this commit:

http://github.com/b4winckler/macvim/commit/c96d4dcc8e5b65bf989efa7e1b86f262974f935c

In another week or so I'll build a new snapshot of MacVim which will include this patch and the one that fixes the bug where MacVim would some times freeze when used with PeepOpen (snapshot 54 already contains this last patch in case anybody had missed that).

**Comment by alecthomas** [comment] 2010-10-05 02:21
Awesome Björn, thanks!

**Comment by b4winckler** [comment] 2010-10-13 11:19
This issue can be closed now, snapshot 55 fixes this problem:

http://github.com/b4winckler/macvim/wiki/ChangeLog

**Comment by jhenderson** [comment] 2010-10-16 18:09
I'm running snapshot 55 and PeepOpen 0.2.4. If I launch MacVim by opening the Gemfile of a rails project for example and then use PeepOpen to open another file, the directory changes. This is preventing PeepOpen from locating other files outside the current directory of the file PeepOpen just opened.

**Comment by b4winckler** [comment] 2010-10-16 20:25
As of snapshot 55 MacVim no longer changes the pwd once a window is already open so you should go through the [Troubleshooting wiki](http://github.com/b4winckler/macvim/wiki/Troubleshooting) to see if some setting of yours is interfering.

Failing that, give me a step-by-step account on how to recreate the problem (without relying on some complex directory structure / ruby specific files etc.).  I doubt that this has anything to do with PeepOpen so please bring the discussion over to [vim_mac](http://groups.google.com/group/vim_mac) as well.  Thanks!

**Comment by daviddavis** [comment] 2010-10-16 23:26
Bjorn, thanks for fixing this. Snapshot 55 is working great with PeepOpen. I've been using it all week and I think this issue can be closed IMO.

**Comment by topfunky** [comment] 2010-10-18 18:00
Should be fixed with MacVim snapshot 55. Thanks to @b4winckler!

**Closed as completed** 2010-10-19 01:00 UTC
Labels: Bug, Planned, v0.2.3, MacVim
