### ISSUE TITLE
Peepcode won't open in MacVIM with space in path

### ISSUE THREAD

**Issue by nevinng** [topfunky/PeepOpen-Issues#234] opened 2011-06-02 07:05 UTC
Background: I'm currenctly using Peepcode 0.3.2 with MacVIM (v7.3.143), Mac OS X 10.6.7

I have a project where it contain space in the path. MacVIM opens the files within the directory just fine. However when I press <Leader>p (i.e. \p) Peepcode won't open. Then I tried to remove the space in the path and the Peepcode works again.

**Comment by netpro2k** [comment] 2011-06-10 16:39
Also seeing this same issue

**Comment by nevinng** [comment] 2011-06-22 09:25
No response whatsoever. Is PeepOpen a dead project?

**Comment by airblade** [comment] 2011-06-22 10:39
This is a duplicate of Issue #236, where I've just posted a fix.

**Comment by topfunky** [comment] 2011-07-01 07:47
Fixing in #236

**Closed as completed by topfunky** 2011-07-01 07:47 UTC
